spring:
  application:
    name: hello-spring-cloud-web-admin-feign
server:
  port: 18765
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
